/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmvault_free: (a: number, b: number) => void;
export const verify: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number) => [number, number, number];
export const wasmvault_approvePairing: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmvault_deleteSecret: (a: number, b: number, c: number) => [number, number];
export const wasmvault_deviceId: (a: number) => [number, number];
export const wasmvault_devicePublic: (a: number) => [number, number, number, number];
export const wasmvault_exists: (a: number) => [number, number, number];
export const wasmvault_fingerprint: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmvault_generateDeviceKey: () => [number, number, number, number];
export const wasmvault_getSecret: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmvault_init: (a: number, b: number, c: number) => [number, number, number];
export const wasmvault_isEnrolled: (a: number) => [number, number, number];
export const wasmvault_issueGrant: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const wasmvault_listDevices: (a: number) => [number, number, number, number];
export const wasmvault_listGrants: (a: number) => [number, number, number, number];
export const wasmvault_listPairing: (a: number) => [number, number, number, number];
export const wasmvault_listSecrets: (a: number) => [number, number, number, number];
export const wasmvault_loadSnapshot: (a: number, b: number, c: number) => [number, number];
export const wasmvault_namespace: (a: number) => [number, number];
export const wasmvault_new: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const wasmvault_putSecret: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const wasmvault_recover: (a: number, b: number, c: number) => [number, number];
export const wasmvault_requestPairing: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmvault_revokeDevice: (a: number, b: number, c: number) => [number, number];
export const wasmvault_revokeGrant: (a: number, b: number, c: number) => [number, number];
export const wasmvault_signChallenge: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const wasmvault_snapshot: (a: number) => [number, number, number, number];
export const wasmvault_verifyAuth: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const wasmvault_verifyGrant: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number];
export const init: () => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
